server:
  port: 8082
spring:
  application:
    name: USER-SERVICE
  datasource:
    driverClassName: org.h2.Driver
    password: root
    username: root
    url: jdbc:h2:mem:wallet
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
